# Generated by Django 5.2.5 on 2025-08-21 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="일정 제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("personal", "개인 PT"),
                            ("group", "그룹 수업"),
                            ("consultation", "상담"),
                            ("other", "기타"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="일정 유형",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                ("start_time", models.TimeField(verbose_name="시작 시간")),
                ("end_time", models.TimeField(verbose_name="종료 시간")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "예약됨"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                            ("no_show", "노쇼"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(default=1, verbose_name="최대 참여자 수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, to="members.member", verbose_name="참여 회원"
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "trainer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당 트레이너",
                    ),
                ),
            ],
            options={
                "verbose_name": "스케줄",
                "verbose_name_plural": "스케줄",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
