# Generated by Django 5.2.5 on 2025-08-21 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("phone", models.CharField(max_length=15, verbose_name="전화번호")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "남성"), ("F", "여성")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="생년월일"),
                ),
                ("join_date", models.DateField(verbose_name="가입일")),
                ("goals", models.TextField(blank=True, verbose_name="운동 목표")),
                (
                    "health_notes",
                    models.TextField(blank=True, verbose_name="건강 특이사항"),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="비상연락처"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "trainer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당 트레이너",
                    ),
                ),
            ],
            options={
                "verbose_name": "회원",
                "verbose_name_plural": "회원",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("daily", "일일권"),
                            ("monthly", "월 회원권"),
                            ("quarterly", "3개월 회원권"),
                            ("yearly", "연간 회원권"),
                            ("pt", "PT 회원권"),
                        ],
                        max_length=20,
                        verbose_name="회원권 유형",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "remaining_sessions",
                    models.IntegerField(default=0, verbose_name="남은 횟수"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="가격"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                        verbose_name="회원",
                    ),
                ),
            ],
            options={
                "verbose_name": "회원권",
                "verbose_name_plural": "회원권",
                "ordering": ["-created_at"],
            },
        ),
    ]
